### ISSUE TITLE
빨버 시간표

### ISSUE THREAD

**Issue by k4sud0n** [hufs-opensw-7/bus-finder#1]
![everytime-web-1702220209715](https://github.com/hufs-opensw-7/bus-finder/assets/58825325/a9cd8821-0e44-497f-a4f6-0953cf49e966)

json 만들때 참고 자료입니다.

**Comment by sungwonnoh** [comment]
json으로 만들고 js파일로 변환하는 것도 고려해보면 좋을 거 같아요
